accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
]

askdjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:post_list'), name='root'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
]

accounts/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    website_url = models.URLField(blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    pass

accounts/views.py
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.shortcuts import redirect, render
from .forms import SignupForm


'''
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # 로그인 처리
            return redirect(settings.LOGIN_URL)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })
'''

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        return resolve_url('profile')

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect(self.get_success_url())

signup = SignupView.as_view()


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post


post_list = ListView.as_view(model=Post)


post_detail = DetailView.as_view(model=Post)

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login.html
<form action="" method="post">
    {% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" />
</form>

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>{{ user }}'s Profile</h2>

    <h3>Bio</h3>
    {{ user.profile.bio|default:"empty" }}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

askdjango/templates/layout.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>AskDjango Blog</title>
</head>
<body>
    <h1>
        <a href="{% url "root" %}">AskDjango Blog</a>
    </h1>

    {% if user.is_authenticated %}
        <a href="{% url "profile" %}">{{ user }}</a>
        <a href="{% url "logout" %}?next={{ request.path }}" onclick="return confirm('Are you sure?');">로그아웃</a>
    {% else %}
        <a href="{% url "signup" %}">회원가입</a>
        <a href="{% url "login" %}?next={{ request.path }}">로그인</a>
    {% endif %}

    <hr/>

    {% block content %}
    {% endblock %}

    <hr/>
    &copy; 2018. AskDjango
</body>
</html>

blog/templates/blog/layout.html
{% extends "layout.html" %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    {{ post.content|linebreaks }}

    <hr/>

    <a href="{% url "blog:post_list" %}">목록</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

    <table>
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        <a href="{% url "blog:post_detail" post.pk %}">
                            {{ post.title }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}